#
#    _______                              ______
#   |__   __|                            / ____|
#      | |  ___ __      __ _ __   _   _ | |      ___   _ __  ___
#      | | / _ \\ \ /\ / /| '_ \ | | | || |     / _ \ | '__|/ _ \
#      | || (_) |\ V  V / | | | || |_| || |____| (_) || |  |  __/
#      |_| \___/  \_/\_/  |_| |_| \__, | \_____|\___/ |_|   \___|
#                                  __/ |
#                                 |___/
#
#    The most customizable Towny expansion plugin for your Towny server!
#                        Developed by Pesto

expansions:

    # Enables the miner kit i.e. full set of iron armor will give infinite haste, fire resistance and night vision
    enable-miner-kit: true

    # Disables post-1.8 combat sounds.
    disable-modern-combat-sounds: true

    # Enables integrations with players using Lunar client providing useful features
    lunar-integration:

        # Enable this expansion. All other settings in this section will be ignored if false
        enabled: true

        # When entering the siege zone, players will be able to see the banner using a specific indicator
        # type. The color of the indicator will use SiegeWar's beacon settings even disabled.
        #
        # Indicator types: none, waypoint, beam
        banner-indicator: 'waypoint'

        # Use Lunar's Team module when entering a siege zone (Requires SiegeWar to be installed)
        team-indicator:
            #









# Do not modify or things will break :p
config-version: 1